// Variáveis globais
const falasDasMaes = [
    // Falas de Gertrudes
    "Hamlet, querido, deixa a tua aparência sombria, E deixa teu olhar parecer amigável para a Dinamarca. Não procure eternamente com as pálpebras abaixadas Por teu nobre pai na poeira. Sabes que é comum. Tudo que vive deve morrer, Passando pela natureza até a eternidade.",
    "Oh, não me fale mais! Estas palavras entram nos meus ouvidos como adagas! Não mais, doce Hamlet!",
    "Tu viraste meus olhos para minha própria alma, E lá vejo manchas negras e vis Como que não sairão de sua cor.",
    "Hamlet, tu ofendeste muito teu pai.",
    "Havia um salgueiro inclinado sobre um riacho, Que mostrava suas folhas brancas na correnteza vívida. Lá, com grinaldas fantásticas, ela veio De ervas-dos-coveiros, urtigas, margaridas e dedaleiras, Que pastores liberais chamam de nome grosseiro, Mas nossas donzelas frias os chamam de dedos de mortos: Lá, nos galhos pendentes, suas guirlandas de coroas Escalando para se pendurarem, uma lasca invejosa quebrou; Quando desceram as suas troféus de ervas, e ela mesma Cairam no riacho choroso. Suas roupas se espalharam largamente; E, como uma sereia, por um tempo eles a sustentaram: Durante esse tempo ela entoou trechos de antigas melodias; Como alguém incapaz de seu próprio sofrimento, Ou como uma criatura nativa e revestida Daquele elemento: mas não poderia ser por muito tempo Até que suas roupas, pesadas com sua bebida, Puxaram a pobre infeliz de sua melodia melodiosa Para a morte lamacenta.",
    "Vem, irmã, senta-te aqui, E conta-me tudo.",
    "Para a minha vergonha, eu juro.",
    "Nação fértil em crimes,",
    "Às vezes, não percebemos o que causamos a nós mesmos.",
  
    // Falas de Lady Macduff
    "Não te lembras da última vez que te deste ao luxo de tal coisa?",
    "Onde está teu pai? Ah, pobre menino!",
    "Pois todos somos homens, na nossa melhor condição, E todos os nossos feitos, virtudes, como disseste, São meras fantasias.",
    "As vozes mais honestas Não têm nada a dizer contra o que fizeste.",
    "Eu não gosto de falar de mim mesma, Mas, como sou, não me tornarei, Até que as flores cresçam e as árvores tenham raízes.",
    "Estou em estado de choque, o que devo dizer?",
    "Miséria, o teu pai é morto!",
    "Que homem poderia enganar tal mulher?",
    "Alguém teve ciúmes da tua boa esposa, Alguém foi injusto comigo.",
    "Agora, Deus te ajude, você tem o meu conforto.",
    "Os gansos estão a salvo, as mães estão em casa.",
    "Deus tenha misericórdia de nós, miserável que sou, Que nenhum amigo nos deixou vivos, A não ser minha própria pessoa.",
    "E, além disso, nosso vaso fraco Isso só serve para ser preso, Que ele deve destruir, separando e sujando",
    "O bom homem morreu, Eu acho que tem sido o inferno para ele.",
    "Eu esperei que você viesse novamente e continuasse isso.",
    "Esses dragões voadores Que para meus olhos trazem lágrimas nas asas.",
    "Está tudo mal. Com tudo isso você não deveria ter partido.",
    "Os olhos dos tolos não podem vê-los como a espada voadora, Até que estejam no seu peito.",
    "Mentiras, todas as mentiras! A coisa mais vilmente mentirosa que se possa inventar!",
    "Dormir, Deus! Se só fossem os mortos.",
  
    // Falas de Hermione
    "Leva-me a ele, minha música, ouvirás.",
    "Eis o ar que deixa os animais fatigados.",
    "Ah, é verdade, se houve algum crime, Como poderia ser disso?",
    "Oh, teu temor, Desse castigo, é puramente imaginação.",
    "Por essa carícia fico recompensada",
    "Mas o que querem eles?",
    "Era casado?",
    "Que culpa posso ter de ser amada por ti?",
    "Alto! Silêncio! Nada mais a dizer.",
    "Sim, até o último pormenor.",
    "Sem que a sua morte seja útil para a minha vida.",
    "Estás apaixonado por ela?",
    "Que homem poderia enganar tal mulher?",
    "Ó, como é difícil dar forma ao pensamento em palavras!",
    "É verdade. Todos sabemos.",
    "Estás apaixonado por ela?",
    "Pede a todos os que ouvirem isto Que cheguem o mais próximo que possam de verdade.",
    "Que horror! Que súbito abalo fez ele tremer.",
    "Que queres dizer com isso? Meu coração está perturbado com este receio.",
    "Foi essa mulher!",
  
    // Falas de Titânia
    "Repreende teu amor, Helena, por minha causa.",
    "Abençoada escuridão! Esconder o estado dos homens",
    "Estou farta de te ouvir. Escapa, espero, para Tebas.",
    "Mas, quando a paz estiver estabelecida, eu aqui Ficar contigo para sempre.",
    "Um lugar, onde as almas atormentadas não encontram Alívio até a partida.",
    "Não te lembras, que me esqueci? Não me lembro de quem sou eu.",
    "Eu acho que é minha conversa. Meu charme é esquecido.",
    "Ó, como amo a tua doçura!",
    "O som da tua voz é música para os meus ouvidos.",
    "Fadas, deixem-no descansar.",
    "O teu bicho-da-seda amarra-te a este lugar.",
    "E as abelhas sem correrem para a tua cor.",
    "Com este teu humor afasta-se de mim.",
    "Odeio a tua cor negra.",
    "Podes separar-me da tua companhia.",
    "Estou feliz, por isso vou acelerar a minha marcha.",
    "Até os veados estão adormecidos nas colinas, E até os pequenos coelhos no campo E as grandes aves da noite com garras afiadas.",
    "E o líquen-cinzento sobre a traça Até a mulher ou homem que descansam com ele Ficam todos encantados. E o veadinho",
    "Salto de dança que muda de cor, E pensa que a estrela do ocaso Está cintilando, Que em sua cor Negra tem alguns olhos de fogo, e isso o perturba.",
    "Muitos são chamados, mas poucos escolhidos.",
    "Não me recordo de ver algo assim.",
    "A noite do pesadelo em vão se aproxima.",
    "Aqui está o fio de seda de cinquenta anos, Cinco tempestades que estavam quentes quando éramos crianças.",
    "Muitos um rosto mais alegre olhando para trás, Com o teatro da minha vida.",
    "Nós somos atores.",
    "Se a gente for sincera.",
    "Tudo é sombra, tudo é farsa.",
    "Um homem brinca um papel em sua vida.",
    "Muitos um ato e todos os homens e mulheres meramente jogadores.",
    "Eles têm suas saídas e suas entradas, E um homem no seu tempo desempenha muitos papéis.",
    "Sua vida é de sete idades. No primeiro, o menino, Com berços brilhantes e brinquedos brilhantes.",
    "Então, o chorão, com uma bolsa e uma cara de bochechas, Cheirando a malte e feno.",
    
    // Falas de Constance
    "Nação fértil em crimes,",
    "Muitos crimes terríveis cometidos em teu nome!",
    "Tu tens uma cabeça de doença oca, e estás louca.",
    "É triste que o meu pobre bebé queira partilhar contigo as suas maldições;",
    "Poços de miséria profundos, rios de lágrimas,",
    "És uma mãe mais cruel do que a tigresa:",
    "Arranca-lhe as entranhas do seu útero.",
    "Tu não tens leite, e deves ter sangue.",
    "Se pudesses continuar, estarias condenada pela tua leiteira.",
    "Ficarias vermelha se tivesses pensamentos maus,",
    "Vergonha, porque uma criança fez isto, uma criança que",
    "Quando o seu pai devia chamar por ti, a chamar por ti.",
    "São as flores da sua bondade que vão fazer um cinto ao redor de",
    "A tua sepultura",
    "e uma abóbada de folhas verdes verdes",
    "Como a tua bondade.",
    "Ó, vês, meu soberano, como está A triste mãe de Dorchester, em Dorchester?",
    "Se chama mãe, seu menino é o Rei de Inglaterra;",
    "Quando está triste, o seu menino é a mãe.",
    "Eis a grande artista de todos!",
    "Aqui, uma pálida, esperando apenas a música. Que, com músicas e brincadeiras, fará sons doces.",
    "Dissipar a tristeza que lhe dá melancolia.",
    "Doce mãe de baixa estatura, uma luta dura, Como uma bagatela morta jogada no rio;",
    "Mas nos seus olhos brilha o aço.",
    "E os lugares baixos são altos com a tua sede.",
    "Seu menino é o único herdeiro de todas as minhas dores, A minha raiva, os meus males;",
    "E aqui eu fico sem mais",
    "A não ser a dignidade do meu alívio, que são as lágrimas. Isto grande monarca da Inglaterra.",
  
    // Falas da mãe de Julieta
    "Tira-me a vida, o mal me foi entregue.",
    "Cruel pai, cruel filho!",
    "Minha filha está morta, minha filha está morta.",
    "Tua filha está morta, minha senhora, na sepultura.",
    "Fui feita para chorar e chorar nunca mais.",
    "Minha querida filha, você era aquela em quem eu mais tinha esperanças,",
    "E vê-la casada com esse pálido e sem graça.",
    "Enterrada na juventude, na flor dos anos,",
    "Noiva da morte, que tem seu amante",
    "Seu amante é tão parecido com a morte quanto ela.",
    "E ela dorme de novo. Oh, cala a boca, cala a boca!",
    "Querida senhora, você tem um coração de pedra?",
    "Perdeu a sua língua. Fala: ela morreu com sua língua.",
    "Eu a amaldiçoo por sua escravidão a ele.",
    "Eu a amaldiçoo por não ser o que eu disse que ela era.",
    "Tua mãe é de paz, não tão bem casada como uma só mulher.",
    "Tua mãe é de paz, em cujo leite tu sugaste; Tua mãe é de paz, cuja leite, por seus mimos,",
    "Enquanto o amor poderia abraçar, formar muito leite e muito alimento.",
    "A mãe é de paz, assim como os tempos estavam,",
    "Tua mãe é de paz, pois amor me fez de ti;",
    "Que o leite de pouca disposição talvez Agradaria a tua mãe de paz, à medida que a ti",
    "E que tua mãe de paz foi minha mãe. Oh, se a minha esposa estivesse morta esta noite,",
    "Ela estaria morta se eu tivesse de ser seu assassino!",
    "Ela se foi, ela está morta; ela está morta, ela está morta.",
    "Ela está morta, ela está morta; a terra tem comido a minha esposa.",
  
    // Falas da mãe de Romeu
    "O que está a fazer? Dizes-me e eu apanho-o.",
    "Ah, o meu pobre filho! Que coração partido!",
    "Adeus, adeus. Que tristeza tu me causaste!",
    "Que dor não traz o filho e o marido!",
    "Romeu, que dia será o meu luto?",
    "Não, nem o meu pai, nem tu, nem ninguém de Monteux,",
    "Para lá, ele foi e para a mesma matança:",
    "Parece que foi ele que cortou-te",
    "Com a parte traseira da espada dela, ou fez-te doente",
    "Da coisa perigosa que ela usava",
    "Foi ele que a magoou, foi ele que matou-te!",
    "A culpa, a culpa está em minha cabeça!",
    "Pela tua natureza, que o dardo da morte atingiu;",
    "Pela falta de sentido da minha natureza, pelo sopro",
    "Que deixou a tua mãe perdida",
    "Deus sabe o que é isso;",
    "Mas que coisa doente ela adquiriu!",
    "Uma febre, febre ou coisa que o lembre,",
    "Que uma coisa feriu, e eu sou feia,",
    "Isto só por causa da dor de tal coisa",
    "Que, o que é isso, pois o seu caso é ferido?",
    "Tem alguma coisa a ver comigo,",
    "E o meu filho também feriu-me!",
    "Seja do que for, diz-me e eu vou responder.",
    "O meu filho, como a que te curar,",
    "Eu continuo a ser atormentado por aquele amor que a ele destroçou",
    "Do corpo dele, e para o teu corpo ele também me destroçou.",
    "A mãe deve morrer, como uma águia,",
    "A quem pensou que as fêmeas o seu coração puxavam,",
    "O meu filho e tu, a mãe e o filho amarrado.",
    "E aquela triste palavra 'banido',",
    "Que uma palavra deve matar todos os Montecchios!",
    "Pois não há linguagem onde a maldade",
    "Não faz eu mesma uma vilã;",
    "Do teu filho e do meu único e herdeiro",
    "O que mais ele pode fazer do que se matar,",
    "Se te matar ele não pode evitar",
    "Mas que tem que fazer? Onde tem que esconder?",
    "Onde deve ter as mãos para não o matar?",
    "Mas mãe, e ele, amparado em mim,",
    "Juro por ti, ele jura que não fez isto.",
    "E aqui me proponho a guardar-me para o meu filho,",
    "E aqui, desafiando a maldição do destino,",
    "Temos este dia a espada deste nobre conde;",
    "Quem quer que seja ferido com isto são meus parentes,",
    "E, sejam eles quem forem, tenho direito a vingar-me;",
    "Mas o meu coração amaldiçoa todo o tipo de armas."
  ];

function mudar_mensagem() {
    const mensagens = document.getElementById('mensagens')
    let aleatorio = Math.floor(Math.random() * falasDasMaes.length)
    mensagens.innerHTML = `<h1>${falasDasMaes[aleatorio]}</h1>`
}

console.log(falasDasMaes.length)